root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server/"
  bin = "./tmp/server"
  full_bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["tmp", "pgdata"]
  delay = 500

[log]
  time = false

[color]
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
